### ISSUE TITLE
Bug: on first load countries list is empty

### ISSUE THREAD

**Issue by Irelynx** [Irelynx/integrify-react#1]
On browser with clean Application Storage (especially CacheStorage), countries page is empty. But if user visits site again or reload the page - everything seems to be fine

**Comment by Irelynx** [comment]
The problem roots seems to be in CacheStorage `put(url, response)` method - it automatically reads the response body, so because of that, when second read attempt of response body happens - it throws an TypeError:
```
TypeError: Failed to execute 'json' on 'Response': body stream already read
    at API.getJSON (index.ts:20:29)
    at async API.getAll (index.ts:58:22)
    at async reload (app.tsx:33:18)
```
